### ISSUE TITLE
Where to use CUDA stream when transferring?

### ISSUE THREAD

**Issue by preordinary** [DataStates/datastates-llm#1]
Thank you for contributing high-quality code! When I scan the code, it is difficult for me to find where using CUDA streams and threads for device-to-host and host-to-file transfers, as the paper shows. I will appreciate if you can point out the position of cuda stream in this repo.

**Comment by mauryaavinash95** [comment]
@preordinary 
The streams for doing D2H and H2D copies are at https://github.com/DataStates/datastates-llm/blob/main/datastates/ckpt/src/tiers/gpu_tier.hpp#L11
The threads for host-to-file and file-to-host are initiated at https://github.com/DataStates/datastates-llm/blob/main/datastates/ckpt/src/tiers/host_tier.cpp#L9
Hope this helps!
